version: "3.8"
services:
  portfolio-sale:
    build: .
    container_name: hackathon
    restart: always
    env_file:
      - .env
    # environment:
    # VITE_APP_BASE_API_URL: http://103.176.146.250:1111
    ports:
      - '3000:3000'
    deploy:
      resources:
        limits:
          cpus: '0.125'
          memory: 2048M
        reservations:
          cpus: '0.125'
          memory: 1024M
